version: '3.7'

services:

  ui:
    container_name: ui
    build:
      context: https://github.com/Sander-N/User-Interface.git
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    networks:
      - frontend

  voting-api:
    container_name: voting-api
    build:
      context: https://github.com/Sander-N/Voting.git
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - frontend
      - messaging

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    networks:
      - db
      - messaging
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - messaging

  db:
    image: postgres:alpine
    container_name: vote-db
    restart: always
    environment:
      - POSTGRES_USER=votinguser
      - POSTGRES_PASSWORD=votingpass
      - POSTGRES_DB=voting
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "voting@app.com"
      PGADMIN_DEFAULT_PASSWORD: "Votingapp1!"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - db
networks:
  frontend:
  messaging:
  db: